
import jsPDF from 'jspdf';

export const generatePaySlip = (data) => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(40);
    doc.text("Monthly Payroll Report", 105, 20, null, null, "center");

    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);

    // Employee Details Section
    doc.setFontSize(12);
    doc.setTextColor(60);

    const startX = 20;
    let startY = 40;
    const lineHeight = 10;

    // Helper to add a row
    const addRow = (label, value) => {
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, startX, startY);
        doc.setFont("helvetica", "normal");
        doc.text(`${value}`, startX + 50, startY);
        startY += lineHeight;
    };

    addRow("Name", data.name);
    addRow("Employee ID", data.empId);
    addRow("Department", data.department || "N/A");
    addRow("Role", data.role || "N/A");
    addRow("Month/Year", `${data.month} ${data.year}`);

    // Financials
    startY += 5; // Extra spacing
    doc.setLineWidth(0.2);
    doc.line(20, startY - 5, 190, startY - 5);

    addRow("Days Present", `${data.daysPresent} Days`);
    addRow("Basic Salary", `INR ${data.basicSalary.toLocaleString()}`);

    // Net Salary Highlight
    startY += 5;
    doc.setFontSize(14);
    doc.setTextColor(0, 100, 0); // Green color
    doc.setFont("helvetica", "bold");
    doc.text("Net Salary:", startX, startY);
    doc.text(`INR ${data.netSalary.toLocaleString()}`, startX + 50, startY);

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Employee Management System", 105, pageHeight - 10, null, null, "center");

    // Save File
    const filename = `PaySlip_${data.month}_${data.year}_${data.empId}.pdf`;
    doc.save(filename);
};
